#!/usr/bin/env node
/**
 * 掘金沸点 CLI 浏览器 - 演示脚本
 * 展示如何使用CLI工具
 */

console.log('🚀 掘金沸点 CLI 浏览器')
console.log('='.repeat(50))
console.log('📖 使用说明:')
console.log('')
console.log('1. 运行CLI工具:')
console.log('   node cli.js')
console.log('')
console.log('2. 全局安装（可选）:')
console.log('   npm link')
console.log('   juejin-pins')
console.log('')
console.log('3. 操作说明:')
console.log('   n - 下一页')
console.log('   p - 上一页')
console.log('   r - 刷新当前页')
console.log('   1-9 - 查看对应序号的沸点详情（包含评论）')
console.log('   q - 退出程序')
console.log('')
console.log('4. 查看评论:')
console.log('   在沸点列表页面，输入数字键（1-9）可以查看')
console.log('   对应序号的沸点详情和所有评论')
console.log('')
console.log('5. 测试功能:')
console.log('   npm test - 测试API连接')
console.log('   npm run test:comments - 测试评论功能')
console.log('')
console.log('='.repeat(50))
console.log('💡 提示: 按 Ctrl+C 可强制退出')
console.log('')